name: FastAPI Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1'           # lunes 03 UTC
  push:
    paths:
      - 'metrics/**'
      - '.github/workflows/metrics.yml'

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r metrics/requirements.txt
          sudo apt-get update && sudo apt-get install -y cloc
      - name: Calidad de código
        run: python metrics/quality_metrics.py
      - name: Métrica MTTR
        run: python metrics/operations_metrics.py
